
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'
hook_source = '''
nnoremap <C-p> :<C-u>FZF<CR>
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


[[plugins]]
repo = 'majutsushi/tagbar'
hook_source = '''
" 启动时自动focus
set tags=./tags,./TAGS,tags;~,TAGS;~
let g:tagbar_autofocus = 1
nmap <F8> :TagbarToggle<CR>
'''
